### PR TITLE
Filter out whitespace entries from the header

### PR DESCRIPTION
**Pull request by cmdcolin**
Seen in #72

### CODE REVIEW

**Comment by cmdcolin** [comment]
Just curious if you think we'd want to not have this for any reason e.g. strictness with respect to spec @garrettjstevens 

If it alright we can prolly just cut a quick release with this

**Review by garrettjstevens — APPROVED** [review]
I think this is fine, since the intent is pretty unambiguous. `bcftools` just removes that tab when viewing, too.

**Comment by cmdcolin** [comment]
:+1: thanks for checking

**Comment by cmdcolin** [comment]
published as 4.0.4

**Pull request merged**
